# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: e2e

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: E2E Test
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2
        
    - name: Create kind cluster
      uses: helm/kind-action@v1.2.0
      with:
        config: .github/workflows/kind/kind.yaml

    - name: init dapr to cluster
      run: docker exec chart-testing-control-plane /bin/bash -c "dapr init -k -n testing"

    - name: init tkeel to cluster
      run: docker exec chart-testing-control-plane /bin/bash -c "tkeel init -k -n testing --debug --timeout 600"

    - name: Install node package to cluster and run e2e test
      run: docker exec chart-testing-control-plane /bin/bash -c "cd /home/tkeel-cli-testing && npm install && npm run test"